### ISSUE TITLE
Add more citation formats

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#10]

**Comment by srickel1** [comment]
I see this as a very low priority. Difficulty will be determined after research

**Comment by srickel1** [comment]
Should not be a difficult addtion.  The system currently only supports APA,MLA and Chicago styles by default.  A little work is needed to add on more - templates and some code tweaking.  

Templates for the new styles will be needed.  

What @unl-libraries/cors  have to do is found at https://vufind.org/wiki/development:howtos:supporting_a_new_citation_style

**Comment by dallison1** [comment]
By template do you mean:
Turabian
Last name, first name, author2 first name last name. date. title in italics, publisher, URL.

Harvard
last name, first initial & author2 last name, first initial date, title in italics publisher.

**Comment by srickel1** [comment]
Yes.  Exactly.  I'll reopen this until we get those entered in.

**Comment by srickel1** [comment]
Added the Harvard citation format, and after looking over the formats, it appears that the Chicago and Turabian are identical for this type of use, so I can change the heading to Chicago/Turabian as I've seen in research guides to cover that. Please look this over @dallison1 and see what you think

**Comment by dallison1** [comment]
- [ ] •   AMA
- [ ] •   APA 6th
- [ ] •   ASA
- [x] •   BibTeX
- [x] •   Chicago/Turabian
- [x] •   Harvard
- [ ] •   MLA 7th
- [ ] •   Vancouver

**Comment by srickel1** [comment]
So far, the citation addition customization is per record driver type (SolrMarc for catalog records, OAI, etc.., and one for EIT - Ebsco).  If we add more sources, we'll have to copy the changes over to all of them as well.   This is because the custom module does not allow us to override the base class (SolrDefault), and retain it locally through upgrades.Only the subclasses can be overridden this way.

 If it's determined to go ahead and do all of the above citation formats, we will need the corresponding layouts/templates for each.

**Comment by srickel1** [comment]
We have received no other templates or information on other citations beyond the checked off items.  We won't pursue this any further until we get that.
