### ISSUE TITLE
harvest digital commons

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#35]

**Comment by srickel1** [comment]
do you have the URL for that?  I thought also if we are just testing it - marcedit has a harvester function we can run it against as well. I also wonder if it's a particular collection/set that it chokes on - it will be easier to diagnose.

**Comment by dallison1** [comment]
Here is the location of a file that has all the URLs for harvesting.  This may come in handy if I’m not around.  It is in the CORS team site:
https://libstaff.unl.edu/sites/cors/_layouts/15/WopiFrame2.aspx?sourcedoc=/sites/cors/Shared%20Documents/harvesting/URLS%20for%20harvested%20collections.docx&action=default

We will need DC in Vufind if go forward anyway so let give it a try.

DeeAnn

**Comment by srickel1** [comment]
Found one problem with the information.  Each record seems to have at least 2 setSpecs - sometimes one does not exist when I retrieve the list of sets via http://digitalcommons.unl.edu/do/oai/?verb=ListSets

These 4 at least
-  publication:publicpolicyfacpub 
- publication:unlreports 
- publication:tractorallischalm 
- publication:ageconrestrict

There was also some bad characters it hit, and I can't tell which record, but I plan to rerun it with a sanitize function on to see if it can strip them out.

**Comment by srickel1** [comment]
BePress reported the following regarding the 4 examples sets we sent as causing issues when we retrieved information:

>  As for the four ‘sets’ that appear to be causing problems, this is likely because they have been hidden. This is why they do not exist in the list of sets, and is likely why they’re having trouble harvesting from those sets. I believe these publications were hidden by administrators to prevent public access

Which seems to indicate we are retrieving records for sets we shouldn't be then.  It's difficult to tell since they all belong to multiple sets, some of which aren't hidden.  I'm not sure how to get around this right now.

**Comment by dallison1** [comment]
I’m not sure they really are hidden, I will have to confirm.

DeeAnn

**Comment by srickel1** [comment]
85,234 digital commons records have been ingested into vufind-dev and are visible at http://vufind-dev.unl.edu/vufind/Search/Results?type=AllFields&filter%5B%5D=institution%3A%22Digital+Commons%22
1. Note the format facet.  I stripped "application/" from the format to get that list.  If you question a format, view the record, and then look at staff view.  The original format was copied into the **recordtype** field.  Over 14,000 have no format at all.
2. Titles have some html tags, most notably italic <i></i>.  I'm sure those were put in for formatting purposes on digital commons, but we will have to decide what to do with them here.  I can try stripping them out. 
3. Authors have all come in as "Last name, First name", and were occassionally used for things like "Parasitology, Journal of" and "Museum, Tractor"  - so should we reformat those into "First name Last name"?
4. Collections - visible as the last facet on the right. Empty ones - with just a dash at the front - will most likely be those sets mentioned above.  They have the setSpec, but no corresponding name since they are hidden.  There are 7,091 of them.
5. Languages - were mapped as best I could.  Would have to have a list of the abbreviations used for that. Examples were "GR" and "GE" and "ES"

**Comment by srickel1** [comment]
These have been harvested, and while there remain many questions as to mapping and the use of the collections, I think we can call this one done.
