### ISSUE TITLE
missing record

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/vufind#47]
this record seems to be missing, it is a 2016 title http://library.unl.edu/record=b4934560
 	The Victor and HMV solo recordings / c José Iturbi
Publication 	[UK] : Appian Publications & Recordings, [2016]
Copyright 	℗2016

**Comment by srickel1** [comment]
This isn't really missing.  It is brand new in the catalog and as we were having issues getting things to index, the automated loads had to be disabled.  We have a workaround for the issue from the vufind folks, that we were just able to test and get working yesterday.  

We still need to force a complete reindex since the call number information is changing, but there are still questions regarding those fields that need to be cleared up before we can reindex and get new records in.

**Comment by dallison1** [comment]
What questions?  Is there something I need to answer?
